server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seven_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.223.129
    port: 6379
    password: asuna
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s